"use client";

import { CalendarDays, Check, Clock3, LoaderCircle, Search, Settings2, UserCheck, UserX, X } from "lucide-react";
import { type FormEvent, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { KpiCard } from "@/components/ui/kpi-card";
import { SuccessToast } from "@/components/ui/toast";

type Summary = { total: number; present: number; late: number; onLeave: number; notPunched: number };
type Row = { id: string; name: string; loginId: string; department: string; punchInAt: string | null; punchOutAt: string | null; status: string; workingHours: number | null };
type RequestItem = { id: string; user: { name: string }; status: string; reason: string; date?: string; startDate?: string; endDate?: string };
type Settings = { officeLatitude: number | null; officeLongitude: number | null; officeRadiusMeters: number | null; visitRadiusMeters: number; lateThresholdMinutes: number; halfDayThresholdHours: number; weeklyOffDays: number[] };
type Holiday = { id: string; date: string; name: string };

const todayKey = () => { const value = new Date(); return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; };
const time = (value: string | null) => value ? new Intl.DateTimeFormat("en-IN", { hour: "numeric", minute: "2-digit", timeZone: "Asia/Kolkata" }).format(new Date(value)) : "—";
const messageFrom = (data: unknown, fallback: string) => data && typeof data === "object" && "message" in data ? String((data as { message: unknown }).message) : fallback;

export function AttendanceAdmin() {
  const [date, setDate] = useState(todayKey()); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [department, setDepartment] = useState("");
  const [summary, setSummary] = useState<Summary | null>(null); const [rows, setRows] = useState<Row[]>([]); const [corrections, setCorrections] = useState<RequestItem[]>([]); const [leaves, setLeaves] = useState<RequestItem[]>([]); const [settings, setSettings] = useState<Settings | null>(null); const [holidays, setHolidays] = useState<Holiday[]>([]);
  const [profile, setProfile] = useState<{ user: { name: string; loginId: string; staffProfile: { employeeCode: string; jobTitle: string } | null }; summary: Record<string, number>; records: Array<{ date: string; status: string; workingHours: number | null }> } | null>(null);
  const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);

  const load = async () => {
    try {
      const params = new URLSearchParams({ date, pageSize: "100" }); if (search) params.set("search", search); if (status) params.set("status", status); if (department) params.set("department", department);
      const urls = [`/api/attendance/admin/today`, `/api/attendance/admin/list?${params}`, "/api/attendance/corrections?status=PENDING", "/api/attendance/leave?status=PENDING", "/api/attendance/settings", "/api/attendance/holidays"];
      const responses = await Promise.all(urls.map((url) => fetch(url, { cache: "no-store" }))); const data = await Promise.all(responses.map((response) => response.json().catch(() => null)));
      const failed = responses.findIndex((response) => !response.ok); if (failed >= 0) throw new Error(messageFrom(data[failed], "Unable to load attendance management."));
      setSummary(data[0]); setRows(data[1].items); setCorrections(data[2]); setLeaves(data[3]); setSettings(data[4]); setHolidays(data[5]); setError("");
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load attendance management."); }
    finally { setLoading(false); }
  };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 200); return () => window.clearTimeout(timer); }, [date, search, status, department]); // eslint-disable-line react-hooks/exhaustive-deps

  const review = async (kind: "corrections" | "leave", id: string, decision: "APPROVED" | "REJECTED") => {
    const response = await fetch(`/api/attendance/${kind}/${id}/review`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: decision }) }); const data = await response.json().catch(() => null); if (!response.ok) return setError(messageFrom(data, "Unable to review request.")); await load(); setNotice(`Request ${decision.toLowerCase()}.`);
  };
  const openProfile = async (id: string) => { const response = await fetch(`/api/attendance/admin/employees/${id}`, { cache: "no-store" }); const data = await response.json().catch(() => null); if (!response.ok) return setError(messageFrom(data, "Unable to load employee attendance.")); setProfile(data); };

  if (loading) return <div className="space-y-3"><div className="h-24 animate-pulse rounded-xl bg-white" /><div className="h-80 animate-pulse rounded-xl bg-white" /></div>;
  return <div className="space-y-5">
    {notice && <SuccessToast message={notice} onClose={() => setNotice("")} />}{error && <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2.5 text-xs text-danger" role="alert">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><KpiCard icon={UserCheck} label="Present" value={summary?.present ?? 0} /><KpiCard icon={Clock3} label="Late" value={summary?.late ?? 0} tone="warning" /><KpiCard icon={CalendarDays} label="On leave" value={summary?.onLeave ?? 0} tone="brand" /><KpiCard icon={UserX} label="Not punched" value={summary?.notPunched ?? 0} tone="danger" /><KpiCard icon={UserCheck} label="Active staff" value={summary?.total ?? 0} /></div>
    <section className="overflow-hidden rounded-xl border bg-white"><div className="grid gap-3 border-b p-4 sm:grid-cols-2 xl:grid-cols-4"><Input type="date" value={date} onChange={(event) => setDate(event.target.value)} /><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-subtle" size={15} /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search staff" /></label><select value={department} onChange={(event) => setDepartment(event.target.value)} className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">All departments</option><option value="SALES">Sales</option><option value="PURCHASE">Purchase</option><option value="ACCOUNTS_BILLING">Accounts & Billing</option><option value="WAREHOUSE">Warehouse</option><option value="DEMO">Demo</option></select><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">All statuses</option>{["PRESENT", "LATE", "HALF_DAY", "ABSENT", "LEAVE", "HOLIDAY", "WEEKLY_OFF", "NOT_PUNCHED"].map((value) => <option key={value}>{value}</option>)}</select></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-[13px]"><thead className="border-b bg-background text-[11px] uppercase tracking-wide text-muted"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Department</th><th className="px-4 py-3">Punch in</th><th className="px-4 py-3">Punch out</th><th className="px-4 py-3">Hours</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y">{rows.map((row) => <tr key={row.id} className="cursor-pointer hover:bg-brand-soft/30" onClick={() => openProfile(row.id)}><td className="px-4 py-3"><p className="font-medium text-foreground">{row.name}</p><p className="text-xs text-muted">{row.loginId}</p></td><td className="px-4 py-3 text-muted">{row.department}</td><td className="px-4 py-3">{time(row.punchInAt)}</td><td className="px-4 py-3">{time(row.punchOutAt)}</td><td className="px-4 py-3">{row.workingHours?.toFixed(2) ?? "—"}</td><td className="px-4 py-3"><span className="rounded-full bg-brand-soft px-2 py-1 text-[10px] font-semibold text-brand-dark">{row.status.replaceAll("_", " ")}</span></td></tr>)}</tbody></table></div>
    </section>
    <div className="grid gap-5 xl:grid-cols-2"><RequestQueue title="Correction approvals" items={corrections} onReview={(id, value) => review("corrections", id, value)} /><RequestQueue title="Leave approvals" items={leaves} onReview={(id, value) => review("leave", id, value)} /></div>
    {settings && <SettingsPanel settings={settings} holidays={holidays} onSaved={async (message) => { await load(); setNotice(message); }} onError={setError} />}
    {profile && <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/40 p-3" role="dialog" aria-modal="true"><div className="max-h-[90dvh] w-full max-w-2xl overflow-y-auto rounded-xl border bg-white"><div className="flex items-start justify-between border-b p-5"><div><h2 className="font-semibold text-foreground">{profile.user.name}</h2><p className="text-xs text-muted">{profile.user.staffProfile?.employeeCode} · {profile.user.staffProfile?.jobTitle}</p></div><button onClick={() => setProfile(null)} className="grid size-8 place-items-center rounded-lg hover:bg-background"><X size={16} /></button></div><div className="grid gap-3 p-5 sm:grid-cols-4">{Object.entries(profile.summary).slice(0, 8).map(([key, value]) => <div key={key} className="rounded-lg border p-3"><p className="text-[10px] uppercase text-muted">{key.replaceAll(/([A-Z])/g, " $1")}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>)}</div><div className="border-t"><h3 className="px-5 py-3 text-sm font-semibold">Monthly history</h3><div className="divide-y">{profile.records.map((record) => <div key={record.date} className="flex items-center justify-between px-5 py-2.5 text-xs"><span>{record.date.slice(0, 10)}</span><span className="text-muted">{record.status.replaceAll("_", " ")} · {record.workingHours?.toFixed(2) ?? "—"}h</span></div>)}</div></div></div></div>}
  </div>;
}

function RequestQueue({ title, items, onReview }: { title: string; items: RequestItem[]; onReview: (id: string, value: "APPROVED" | "REJECTED") => void }) { return <section className="overflow-hidden rounded-xl border bg-white"><div className="border-b px-4 py-3"><h2 className="text-sm font-semibold">{title}</h2></div>{items.length ? <div className="divide-y">{items.map((item) => <div key={item.id} className="p-4"><p className="text-sm font-medium">{item.user.name}</p><p className="mt-1 text-xs text-muted">{item.reason}</p><div className="mt-3 flex gap-2"><Button className="h-8 px-3 text-xs" onClick={() => onReview(item.id, "APPROVED")}><Check size={13} />Approve</Button><Button variant="secondary" className="h-8 px-3 text-xs" onClick={() => onReview(item.id, "REJECTED")}><X size={13} />Reject</Button></div></div>)}</div> : <p className="p-6 text-center text-xs text-muted">Nothing pending.</p>}</section>; }

function SettingsPanel({ settings, holidays, onSaved, onError }: { settings: Settings; holidays: Holiday[]; onSaved: (message: string) => Promise<void>; onError: (message: string) => void }) {
  const [form, setForm] = useState({ officeLatitude: settings.officeLatitude?.toString() ?? "", officeLongitude: settings.officeLongitude?.toString() ?? "", officeRadiusMeters: settings.officeRadiusMeters?.toString() ?? "", visitRadiusMeters: settings.visitRadiusMeters.toString(), lateThresholdMinutes: settings.lateThresholdMinutes.toString(), halfDayThresholdHours: settings.halfDayThresholdHours.toString(), weeklyOffDays: settings.weeklyOffDays });
  const [holidayDate, setHolidayDate] = useState(""); const [holidayName, setHolidayName] = useState(""); const [busy, setBusy] = useState(false);
  const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); const payload = { officeLatitude: form.officeLatitude ? Number(form.officeLatitude) : null, officeLongitude: form.officeLongitude ? Number(form.officeLongitude) : null, officeRadiusMeters: form.officeRadiusMeters ? Number(form.officeRadiusMeters) : null, visitRadiusMeters: Number(form.visitRadiusMeters), lateThresholdMinutes: Number(form.lateThresholdMinutes), halfDayThresholdHours: Number(form.halfDayThresholdHours), weeklyOffDays: form.weeklyOffDays }; const response = await fetch("/api/attendance/settings", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => null); setBusy(false); if (!response.ok) return onError(messageFrom(data, "Unable to save settings.")); await onSaved("Attendance settings saved."); };
  const addHoliday = async () => { const response = await fetch("/api/attendance/holidays", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ date: holidayDate, name: holidayName }) }); const data = await response.json().catch(() => null); if (!response.ok) return onError(messageFrom(data, "Unable to add holiday.")); setHolidayDate(""); setHolidayName(""); await onSaved("Holiday saved."); };
  const removeHoliday = async (id: string) => { if (!window.confirm("Remove this holiday?")) return; const response = await fetch(`/api/attendance/holidays/${id}`, { method: "DELETE" }); if (!response.ok) return onError("Unable to remove holiday."); await onSaved("Holiday removed."); };
  return <section className="rounded-xl border bg-white p-4 sm:p-5"><div className="flex items-center gap-2"><Settings2 size={17} className="text-brand" /><h2 className="text-sm font-semibold">Attendance settings</h2></div><form onSubmit={save} className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{(["officeLatitude", "officeLongitude", "officeRadiusMeters", "visitRadiusMeters", "lateThresholdMinutes", "halfDayThresholdHours"] as const).map((key) => <label key={key} className="space-y-1"><span className="text-xs font-medium text-muted">{key.replaceAll(/([A-Z])/g, " $1")}</span><Input type="number" step={key.includes("Latitude") || key.includes("Longitude") || key === "halfDayThresholdHours" ? "any" : "1"} value={form[key]} onChange={(event) => setForm((value) => ({ ...value, [key]: event.target.value }))} /></label>)}<div className="sm:col-span-2 xl:col-span-3"><p className="mb-2 text-xs font-medium text-muted">Weekly off</p><div className="flex flex-wrap gap-2">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((label, day) => <label key={label} className="flex items-center gap-1.5 rounded-lg border px-2.5 py-2 text-xs"><input type="checkbox" checked={form.weeklyOffDays.includes(day)} onChange={(event) => setForm((value) => ({ ...value, weeklyOffDays: event.target.checked ? [...value.weeklyOffDays, day] : value.weeklyOffDays.filter((item) => item !== day) }))} />{label}</label>)}</div></div><div className="sm:col-span-2 xl:col-span-3"><Button disabled={busy}>{busy && <LoaderCircle className="animate-spin" size={14} />}Save settings</Button></div></form><div className="mt-6 border-t pt-4"><h3 className="text-sm font-semibold">Holidays</h3><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Input type="date" value={holidayDate} onChange={(event) => setHolidayDate(event.target.value)} /><Input value={holidayName} onChange={(event) => setHolidayName(event.target.value)} placeholder="Holiday name" /><Button type="button" disabled={!holidayDate || !holidayName} onClick={addHoliday}>Add</Button></div><div className="mt-3 divide-y rounded-lg border">{holidays.map((holiday) => <div key={holiday.id} className="flex items-center justify-between gap-3 px-3 py-2.5"><p className="text-xs"><strong>{holiday.name}</strong> · {holiday.date.slice(0, 10)}</p><button onClick={() => removeHoliday(holiday.id)} className="text-xs text-danger">Remove</button></div>)}</div></div></section>;
}
