"use client";

import { Camera, CheckCircle2, ClipboardList, MapPin, Search, ShoppingCart, Target, X } from "lucide-react";
import Image from "next/image";
import { useEffect, useState } from "react";
import { Input } from "@/components/ui/input";
import { KpiCard } from "@/components/ui/kpi-card";

type Visit = { id: string; status: string; route: { routeDate: string; staff: { id: string; name: string } }; client: { salonName: string; city: string; area: string | null; territory?: string | null }; activity: { checkInAt: string | null; checkOutAt: string | null; visitOutcome: string | null; visitProof: { distanceMeters: number | null; gpsVerified: boolean | null; capturedAt: string } | null } | null };
type ResponseData = { summary: { total: number; completed: number; pending: number; gpsVerified: number; photoCaptured: number; productive: number; ordersGenerated: number }; items: Visit[]; filters: { staff: Array<{ id: string; name: string }>; territories: string[] } };
type Evidence = Visit & { activity: NonNullable<Visit["activity"]> & { personMet: string | null; purpose: string | null; note: string | null; nextAction: string | null; visitProof: { distanceMeters: number | null; gpsVerified: boolean | null; capturedAt: string; checkInLatitude: string; checkInLongitude: string; checkInPhotoMime: string; checkOutDistanceMeters: number | null; checkOutGpsVerified: boolean | null; checkedOutAt: string | null; checkOutLatitude: string | null; checkOutLongitude: string | null; checkOutPhotoMime: string | null } | null } };

const todayKey = () => { const value = new Date(); return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; };
const time = (value: string | null) => value ? new Intl.DateTimeFormat("en-IN", { hour: "numeric", minute: "2-digit", timeZone: "Asia/Kolkata" }).format(new Date(value)) : "—";

export function FieldActivityAdmin() {
  const [date, setDate] = useState(todayKey()); const [search, setSearch] = useState(""); const [gps, setGps] = useState(""); const [staffId, setStaffId] = useState(""); const [territory, setTerritory] = useState(""); const [status, setStatus] = useState(""); const [data, setData] = useState<ResponseData | null>(null); const [evidence, setEvidence] = useState<Evidence | null>(null); const [error, setError] = useState("");
  const load = async () => { const params = new URLSearchParams(); if (date) params.set("date", date); if (search) params.set("search", search); if (gps) params.set("gps", gps); if (staffId) params.set("staffId", staffId); if (territory) params.set("territory", territory); if (status) params.set("status", status); try { const response = await fetch(`/api/routes/admin/visits?${params}`, { cache: "no-store" }); const json = await response.json().catch(() => null); if (!response.ok) throw new Error(json?.message ?? "Unable to load field activity."); setData(json); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load field activity."); } };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 200); return () => window.clearTimeout(timer); }, [date, search, gps, staffId, territory, status]); // eslint-disable-line react-hooks/exhaustive-deps
  const openEvidence = async (id: string) => { const response = await fetch(`/api/routes/admin/visits/${id}`, { cache: "no-store" }); const json = await response.json().catch(() => null); if (!response.ok) return setError(json?.message ?? "Unable to load visit evidence."); setEvidence(json); };
  const summary = data?.summary;
  return <div className="space-y-5">
    {error && <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2.5 text-xs text-danger" role="alert">{error}</div>}
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-7"><KpiCard icon={ClipboardList} label="Visits" value={summary?.total ?? 0} /><KpiCard icon={CheckCircle2} label="Completed" value={summary?.completed ?? 0} tone="success" /><KpiCard icon={Target} label="Pending" value={summary?.pending ?? 0} tone="warning" /><KpiCard icon={MapPin} label="GPS verified" value={summary?.gpsVerified ?? 0} tone="brand" /><KpiCard icon={Camera} label="Photos" value={summary?.photoCaptured ?? 0} /><KpiCard icon={Target} label="Productive" value={summary?.productive ?? 0} tone="success" /><KpiCard icon={ShoppingCart} label="Orders" value={summary?.ordersGenerated ?? 0} tone="brand" /></div>
    <section className="crm-surface overflow-hidden"><div className="grid gap-3 border-b p-4 sm:grid-cols-2 xl:grid-cols-6"><Input type="date" value={date} onChange={(event) => setDate(event.target.value)} /><label className="relative xl:col-span-2"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-subtle" size={15} /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search salon" /></label><select value={staffId} onChange={(event) => setStaffId(event.target.value)} className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">All staff</option>{data?.filters.staff.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={territory} onChange={(event) => setTerritory(event.target.value)} className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">All territories</option>{data?.filters.territories.map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">All statuses</option><option value="PLANNED">In progress</option><option value="VISITED">Completed</option></select><select value={gps} onChange={(event) => setGps(event.target.value)} className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">All GPS</option><option value="verified">Verified</option><option value="outside">Outside radius</option><option value="skipped">Not configured</option></select></div>
      <div className="divide-y">{data?.items.length ? data.items.map((visit) => <button key={visit.id} type="button" onClick={() => openEvidence(visit.id)} className="grid w-full gap-2 px-4 py-3 text-left hover:bg-brand-soft/30 sm:grid-cols-[1.4fr_1fr_1fr_auto] sm:items-center"><div><p className="text-sm font-medium text-foreground">{visit.client.salonName}</p><p className="text-xs text-muted">{[visit.client.area, visit.client.city].filter(Boolean).join(" · ")}</p></div><p className="text-xs text-muted">{visit.route.staff.name}</p><p className="text-xs text-muted">{time(visit.activity?.checkInAt ?? null)} – {time(visit.activity?.checkOutAt ?? null)}</p><span className={`w-fit rounded-full px-2 py-1 text-[10px] font-semibold ${visit.activity?.visitProof?.gpsVerified === true ? "bg-success-soft text-success" : visit.activity?.visitProof?.gpsVerified === false ? "bg-red-50 text-danger" : "bg-gray-100 text-muted"}`}>{visit.activity?.visitProof?.gpsVerified === true ? `${visit.activity.visitProof.distanceMeters}m · Verified` : visit.activity?.visitProof?.gpsVerified === false ? `${visit.activity.visitProof.distanceMeters}m · Outside` : "GPS skipped"}</span></button>) : <p className="p-10 text-center text-xs text-muted">No field visits match these filters.</p>}</div>
    </section>
    {evidence && <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/40 p-3" role="dialog" aria-modal="true"><div className="max-h-[92dvh] w-full max-w-3xl overflow-y-auto rounded-xl border bg-white"><div className="flex items-start justify-between border-b p-5"><div><h2 className="font-semibold text-foreground">{evidence.client.salonName}</h2><p className="text-xs text-muted">{evidence.route.staff.name} · {evidence.route.routeDate.slice(0, 10)}</p></div><button onClick={() => setEvidence(null)} className="grid size-8 place-items-center rounded-lg hover:bg-background"><X size={16} /></button></div>
      <div className="grid gap-4 p-5 sm:grid-cols-2">
        <div>
          <p className="mb-1.5 text-xs font-semibold uppercase tracking-wide text-muted">Check-in</p>
          <div className="relative aspect-[4/3] overflow-hidden rounded-xl border bg-background">{evidence.activity.visitProof ? <Image src={`/api/routes/stops/${evidence.id}/photo?kind=in`} alt={`Check-in at ${evidence.client.salonName}`} fill unoptimized className="object-cover" /> : <div className="grid h-full place-items-center text-xs text-muted">No photo</div>}</div>
          <dl className="mt-2 grid grid-cols-2 gap-2 text-xs"><div><dt className="text-muted">Time</dt><dd className="font-medium text-foreground">{time(evidence.activity.checkInAt)}</dd></div><div><dt className="text-muted">GPS</dt><dd className="font-medium text-foreground">{evidence.activity.visitProof?.distanceMeters == null ? "Not configured" : `${evidence.activity.visitProof.distanceMeters}m · ${evidence.activity.visitProof.gpsVerified ? "Verified" : "Outside radius"}`}</dd></div></dl>
        </div>
        <div>
          <p className="mb-1.5 text-xs font-semibold uppercase tracking-wide text-muted">Check-out</p>
          <div className="relative aspect-[4/3] overflow-hidden rounded-xl border bg-background">{evidence.activity.visitProof?.checkOutPhotoMime ? <Image src={`/api/routes/stops/${evidence.id}/photo?kind=out`} alt={`Check-out at ${evidence.client.salonName}`} fill unoptimized className="object-cover" /> : <div className="grid h-full place-items-center text-xs text-muted">{evidence.activity.checkOutAt ? "No photo" : "Visit in progress"}</div>}</div>
          <dl className="mt-2 grid grid-cols-2 gap-2 text-xs"><div><dt className="text-muted">Time</dt><dd className="font-medium text-foreground">{time(evidence.activity.checkOutAt)}</dd></div><div><dt className="text-muted">GPS</dt><dd className="font-medium text-foreground">{evidence.activity.visitProof?.checkOutDistanceMeters == null ? "Not configured" : `${evidence.activity.visitProof.checkOutDistanceMeters}m · ${evidence.activity.visitProof.checkOutGpsVerified ? "Verified" : "Outside radius"}`}</dd></div></dl>
        </div>
      </div>
      <dl className="grid gap-3 border-t p-5 sm:grid-cols-2">{[["Outcome", evidence.activity.visitOutcome?.replaceAll("_", " ") ?? "In progress"], ["Person met", evidence.activity.personMet ?? "—"], ["Next action", evidence.activity.nextAction ?? "—"], ["Notes", evidence.activity.note ?? "—"]].map(([label, value]) => <div key={label} className="border-b pb-2"><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 text-sm font-medium text-foreground">{value}</dd></div>)}</dl>
    </div></div>}
  </div>;
}
