"use client";

import { Banknote, CheckCircle2, ChevronLeft, ChevronRight, Download, FileText, IndianRupee, ReceiptText, Search, Send, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { KpiCard } from "@/components/ui/kpi-card";

type Invoice = { id: string; invoiceNumber: string; status: string; subtotal: string; discountAmount: string; taxAmount: string; totalAmount: string; amountPaid: string; balanceDue: string; issuedAt: string; dueDate: string; sentAt: string | null; paidAt: string | null; notes: string | null; client: { id: string; salonName: string; city: string }; order: { id: string; orderNumber: string; salesperson: { name: string } }; generatedBy: { name: string }; items: Array<{ id: string; productName: string; sku: string; quantity: number; unit: string; gstRate: string; lineTotal: string }>; payments: Array<{ id: string; paymentDate: string; amount: string; mode: string; reference: string | null; recordedBy: { name: string } }> };
export type InvoiceListResponse = { items: Invoice[]; page: number; pageSize: number; total: number; hasMore: boolean };
const money = (value: string | number) => `₹${Number(value).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const pretty = (value: string) => value.toLowerCase().split("_").map((part) => part[0].toUpperCase() + part.slice(1)).join(" ");
const date = (value: string) => new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(value));
const messageFrom = (data: unknown, fallback: string) => data && typeof data === "object" && "message" in data ? String((data as { message: unknown }).message) : fallback;

export function InvoicesModule({ initial, canManage }: { initial: InvoiceListResponse | null; canManage: boolean }) {
  const [data, setData] = useState(initial); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<Invoice | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(initial ? "" : "Unable to load invoices.");
  const load = async (targetPage = page) => { setLoading(true); try { const params = new URLSearchParams({ page: String(targetPage), pageSize: "20" }); if (search.trim()) params.set("search", search.trim()); const response = await fetch(`/api/billing/invoices?${params}`, { cache: "no-store" }); const json = await response.json().catch(() => null); if (!response.ok) throw new Error(messageFrom(json, "Unable to load invoices.")); setData(json); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load invoices."); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(() => { setPage(1); void load(1); }, 300); return () => clearTimeout(timer); }, [search]); // eslint-disable-line react-hooks/exhaustive-deps
  const totals = useMemo(() => data?.items.reduce((value, invoice) => ({ billed: value.billed + Number(invoice.totalAmount), paid: value.paid + Number(invoice.amountPaid), due: value.due + Number(invoice.balanceDue) }), { billed: 0, paid: 0, due: 0 }) ?? { billed: 0, paid: 0, due: 0 }, [data]);
  return <div className="space-y-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><KpiCard icon={ReceiptText} label="Billed" value={money(totals.billed)} detail="Current page" /><KpiCard icon={CheckCircle2} label="Received" value={money(totals.paid)} detail="Current page" tone="success" /><KpiCard icon={IndianRupee} label="Outstanding" value={money(totals.due)} detail="Current page" tone="warning" /></div>
    <section className="crm-surface overflow-hidden"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold text-foreground">Invoices</h2><p className="mt-0.5 text-xs text-muted">{data?.total ?? 0} invoice{data?.total === 1 ? "" : "s"}</p></div><label className="relative w-full sm:w-72"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-subtle" size={16} /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Invoice, order or customer" className="pl-9" /></label></div>
      {error && <div className="m-4 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-danger">{error}</div>}
      <div className="divide-y">{data?.items.map((invoice) => <button type="button" key={invoice.id} onClick={() => setSelected(invoice)} className="grid w-full gap-3 p-4 text-left hover:bg-background/70 sm:grid-cols-[1.2fr_1fr_auto_auto] sm:items-center sm:px-5"><div><p className="text-sm font-semibold text-foreground">{invoice.invoiceNumber}</p><p className="mt-0.5 text-xs text-muted">{invoice.order.orderNumber} · {date(invoice.issuedAt)}</p></div><div><p className="text-sm font-medium text-foreground">{invoice.client.salonName}</p><p className="text-xs text-muted">{invoice.client.city}</p></div><Status value={invoice.status} /><div className="text-left sm:min-w-28 sm:text-right"><p className="text-sm font-semibold text-foreground">{money(invoice.totalAmount)}</p><p className="text-xs text-muted">Due {money(invoice.balanceDue)}</p></div></button>)}{!loading && !data?.items.length && <div className="px-5 py-14 text-center"><FileText className="mx-auto text-subtle" size={28} /><p className="mt-3 text-sm font-semibold">No invoices found</p><p className="mt-1 text-xs text-muted">Invoices appear after Accounts approves an order draft.</p></div>}</div>
      {data && data.total > data.pageSize && <div className="flex items-center justify-between border-t px-4 py-3"><p className="text-xs text-muted">Page {data.page} of {Math.ceil(data.total / data.pageSize)}</p><div className="flex gap-2"><Button variant="secondary" disabled={page <= 1 || loading} onClick={() => { const next = page - 1; setPage(next); void load(next); }}><ChevronLeft size={15} />Previous</Button><Button variant="secondary" disabled={!data.hasMore || loading} onClick={() => { const next = page + 1; setPage(next); void load(next); }}>Next<ChevronRight size={15} /></Button></div></div>}
    </section>{selected && <InvoiceDrawer invoice={selected} canManage={canManage} onClose={() => setSelected(null)} onChanged={async (invoice) => { setSelected(invoice); await load(); }} />}</div>;
}
function Status({ value }: { value: string }) { const tone = value === "PAID" ? "bg-success-soft text-success" : value === "OVERDUE" ? "bg-red-50 text-danger" : value === "PARTIALLY_PAID" ? "bg-warning-soft text-warning" : "bg-brand-soft text-brand"; return <span className={`w-fit rounded-full px-2.5 py-1 text-[11px] font-semibold ${tone}`}>{pretty(value)}</span>; }

function InvoiceDrawer({ invoice, canManage, onClose, onChanged }: { invoice: Invoice; canManage: boolean; onClose: () => void; onChanged: (value: Invoice) => Promise<void> }) {
  const [paymentOpen, setPaymentOpen] = useState(false); const [amount, setAmount] = useState(invoice.balanceDue); const [paymentDate, setPaymentDate] = useState(new Date().toISOString().slice(0, 10)); const [mode, setMode] = useState("BANK_TRANSFER"); const [reference, setReference] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const action = async (kind: "sent" | "payment") => { setBusy(true); setError(""); try { const response = await fetch(kind === "sent" ? `/api/billing/invoices/${invoice.id}/status` : `/api/billing/invoices/${invoice.id}/payments`, { method: kind === "sent" ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(kind === "sent" ? { status: "SENT" } : { paymentDate, amount: Number(amount), mode, reference: reference.trim() || undefined }) }); const json = await response.json().catch(() => null); if (!response.ok) throw new Error(messageFrom(json, "Unable to update invoice.")); setPaymentOpen(false); await onChanged(json as Invoice); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update invoice."); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-50 flex justify-end bg-foreground/35 backdrop-blur-[1px]"><div className="flex h-full w-full max-w-2xl flex-col bg-white shadow-2xl"><div className="flex items-start justify-between border-b px-5 py-4"><div><div className="flex items-center gap-2"><h2 className="text-base font-semibold">{invoice.invoiceNumber}</h2><Status value={invoice.status} /></div><p className="mt-1 text-xs text-muted">{invoice.client.salonName} · Due {date(invoice.dueDate)}</p></div><button onClick={onClose} className="grid size-9 place-items-center rounded-lg text-muted hover:bg-background"><X size={18} /></button></div>
    <div className="flex-1 space-y-5 overflow-y-auto p-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Mini label="Invoice total" value={money(invoice.totalAmount)} /><Mini label="Amount paid" value={money(invoice.amountPaid)} /><Mini label="Balance due" value={money(invoice.balanceDue)} /></div><div className="overflow-hidden rounded-lg border">{invoice.items.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 border-b p-3 last:border-0"><div><p className="text-sm font-medium">{item.productName}</p><p className="text-xs text-muted">{item.sku} · {item.quantity} {item.unit} · GST {Number(item.gstRate)}%</p></div><p className="text-sm font-semibold">{money(item.lineTotal)}</p></div>)}</div>
      {invoice.payments.length > 0 && <div><h3 className="mb-2 text-sm font-semibold">Payment history</h3><div className="space-y-2">{invoice.payments.map((payment) => <div key={payment.id} className="flex items-center justify-between rounded-lg border px-3 py-2.5"><div><p className="text-xs font-medium">{pretty(payment.mode)} · {date(payment.paymentDate)}</p><p className="text-[11px] text-muted">{payment.reference || "No reference"} · {payment.recordedBy.name}</p></div><p className="text-sm font-semibold text-success">{money(payment.amount)}</p></div>)}</div></div>}
      {paymentOpen && <div className="rounded-lg border bg-background p-4"><h3 className="text-sm font-semibold">Record payment</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="space-y-1.5"><span className="text-xs font-medium">Payment date</span><Input type="date" value={paymentDate} onChange={(event) => setPaymentDate(event.target.value)} /></label><label className="space-y-1.5"><span className="text-xs font-medium">Amount received</span><Input type="number" min="0.01" max={invoice.balanceDue} step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label className="space-y-1.5"><span className="text-xs font-medium">Payment mode</span><select value={mode} onChange={(event) => setMode(event.target.value)} className="h-10 w-full rounded-lg border bg-white px-3 text-sm"><option value="BANK_TRANSFER">Bank transfer</option><option value="UPI">UPI</option><option value="CHEQUE">Cheque</option><option value="CASH">Cash</option><option value="CARD">Card</option><option value="OTHER">Other</option></select></label><label className="space-y-1.5"><span className="text-xs font-medium">Reference</span><Input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="UTR / cheque / transaction no." /></label></div><div className="mt-3 flex justify-end gap-2"><Button variant="secondary" onClick={() => setPaymentOpen(false)}>Cancel</Button><Button disabled={busy || !Number(amount)} onClick={() => action("payment")}><Banknote size={15} />Save payment</Button></div></div>}{error && <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-danger">{error}</div>}
    </div><div className="flex flex-wrap justify-end gap-2 border-t p-4"><a href={`/api/billing/invoices/${invoice.id}/pdf`} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center gap-2 rounded-lg border px-3 text-sm font-semibold text-foreground hover:bg-background"><Download size={15} />Invoice PDF</a>{canManage && invoice.status === "GENERATED" && <Button variant="secondary" disabled={busy} onClick={() => action("sent")}><Send size={15} />Mark sent</Button>}{canManage && Number(invoice.balanceDue) > 0 && <Button disabled={busy} onClick={() => setPaymentOpen(true)}><IndianRupee size={15} />Record payment</Button>}</div></div></div>;
}
function Mini({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-background p-3"><p className="text-[11px] font-medium text-muted">{label}</p><p className="mt-1 text-base font-semibold">{value}</p></div>; }
