"use client";
import { Camera, Check, FileUp, Truck, XCircle } from "lucide-react";
import { useEffect, useState } from "react";
import type { ReplenishmentRequest } from "@/components/distributor-replenishment";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
const messageFrom = (data: unknown, fallback: string) => data && typeof data === "object" && "message" in data ? String((data as { message: unknown }).message) : fallback;
export function PartnerReplenishmentConfirmation({ token }: { token: string }) {
  const [request, setRequest] = useState<ReplenishmentRequest | null>(null); const [invoice, setInvoice] = useState(""); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [quantities, setQuantities] = useState<Record<string, number>>({});
  useEffect(() => { let active = true; void fetch(`/api/partner/replenishment/${token}`, { cache: "no-store" }).then(async (response) => { const data = await response.json().catch(() => null); if (!response.ok) throw new Error(messageFrom(data, "Unable to open this request.")); if (active) setRequest(data); }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "Unable to open this request."); }); return () => { active = false; }; }, [token]);
  const act = async (action: "approve" | "reject" | "fulfill") => { if (!request) return; setBusy(true); setError(""); try { if (action === "fulfill" && file) { const body = new FormData(); body.set("invoice", file); const upload = await fetch(`/api/partner/replenishment/${token}/invoice`, { method: "POST", body }); const json = await upload.json().catch(() => null); if (!upload.ok) throw new Error(messageFrom(json, "Unable to upload invoice.")); } const response = await fetch(`/api/partner/replenishment/${token}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, ...(action === "approve" ? { items: request.items.map((item) => ({ itemId: item.id, quantity: quantities[item.id] ?? item.quantity })) } : {}), ...(action === "reject" ? { comment: "Rejected by supplying partner" } : {}), ...(action === "fulfill" ? { invoiceReference: invoice.trim() } : {}) }) }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(messageFrom(data, "Unable to update this request.")); setRequest(data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update this request."); } finally { setBusy(false); } };
  if (!request) return <main className="grid min-h-dvh place-items-center bg-[#F5F6F6] p-4"><div className="w-full max-w-md rounded-xl border bg-white p-6 text-sm text-muted">{error || "Opening secure request…"}</div></main>;
  return <main className="min-h-dvh bg-[#F5F6F6] p-4 sm:py-10"><section className="mx-auto max-w-xl overflow-hidden rounded-xl border bg-white"><div className="border-b p-5"><p className="text-xs font-semibold uppercase tracking-wider text-muted">Bond Therapy replenishment</p><div className="mt-1 flex justify-between gap-3"><h1 className="text-xl font-semibold">{request.requestNumber}</h1><span className="rounded-full bg-background px-2.5 py-1 text-xs font-semibold">{request.status.replaceAll("_", " ")}</span></div><p className="mt-1 text-sm text-muted">{request.sourceDistributor?.businessName} → {request.distributor.businessName}</p></div><div className="space-y-4 p-5"><div className="space-y-2">{request.items.map((item) => <label key={item.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><span className="min-w-0 truncate text-sm">{item.product.name}</span>{request.status === "REQUESTED" ? <Input className="h-8 w-20 text-right" type="number" min={0} max={item.quantity} value={quantities[item.id] ?? item.quantity} onChange={(event) => setQuantities((current) => ({ ...current, [item.id]: Number(event.target.value) }))} /> : <span className="text-sm font-semibold">{item.acceptedQuantity ?? item.quantity}</span>}</label>)}</div>{request.status === "REQUESTED" && <div className="flex gap-2"><Button disabled={busy} onClick={() => act("approve")}><Check size={15} />Accept</Button><Button variant="secondary" disabled={busy} onClick={() => act("reject")}><XCircle size={15} />Reject</Button></div>}{["APPROVED", "PICKING", "PACKED"].includes(request.status) && <div className="space-y-3"><Input value={invoice} onChange={(event) => setInvoice(event.target.value)} placeholder="Tally / Marg invoice number" /><div className="grid grid-cols-2 gap-2"><label className="flex h-11 cursor-pointer items-center justify-center gap-2 rounded-lg border px-3 text-sm font-medium"><Camera size={16} />Take photo<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" className="sr-only" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label><label className="flex h-11 cursor-pointer items-center justify-center gap-2 rounded-lg border px-3 text-sm font-medium"><FileUp size={16} />PDF / photo<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="sr-only" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label></div>{file && <p className="truncate text-xs text-muted">Added: {file.name}</p>}<Button disabled={busy || !invoice.trim() || !file} onClick={() => act("fulfill")}><Truck size={15} />Confirm dispatch</Button></div>}{error && <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-danger">{error}</div>}</div></section></main>;
}
