"use client";

import { Camera, Check, FileUp, PackageCheck, XCircle } from "lucide-react";
import { useState } from "react";
import type { Order } from "@/components/orders-module";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { prepareInvoiceFile } from "@/lib/invoice-file";

const messageFrom = (data: unknown, fallback: string) => data && typeof data === "object" && "message" in data ? String((data as { message: unknown }).message) : fallback;

export function PartnerOrderConfirmation({ token, initial, initialError = "" }: { token: string; initial: Order | null; initialError?: string }) {
  const [order, setOrder] = useState<Order | null>(initial); const [invoice, setInvoice] = useState(""); const [file, setFile] = useState<File | null>(null); const [comment, setComment] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(initialError);
  const update = async (status: string) => { if (!order) return; setBusy(true); setError(""); try { if (status === "DISTRIBUTOR_FULFILLED") { if (!file || !invoice.trim()) throw new Error("Add the invoice number and invoice file first."); const body = new FormData(); body.set("invoice", await prepareInvoiceFile(file)); const upload = await fetch(`/api/partner/orders/${token}/invoice`, { method: "POST", body }); const uploadData = await upload.json().catch(() => null); if (!upload.ok) throw new Error(messageFrom(uploadData, "Unable to upload invoice.")); } const response = await fetch(`/api/partner/orders/${token}/status`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status, version: order.version, comment: comment.trim() || undefined, ...(status === "DISTRIBUTOR_FULFILLED" ? { distributorInvoiceReference: invoice.trim() } : {}) }) }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(messageFrom(data, "Unable to update order.")); setOrder(data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update order."); } finally { setBusy(false); } };
  if (!order) return <main className="grid min-h-dvh place-items-center bg-[#F5F6F6] p-4"><div className="w-full max-w-md rounded-xl border bg-white p-6 text-center"><p className="text-sm text-muted">{error || "Opening secure order…"}</p>{error && <Button className="mt-4" onClick={() => window.location.reload()}>Try again</Button>}</div></main>;
  return <main className="min-h-dvh bg-[#F5F6F6] p-4 sm:py-10"><section className="mx-auto w-full max-w-xl overflow-hidden rounded-xl border bg-white"><div className="border-b p-5"><p className="text-xs font-semibold uppercase tracking-wider text-muted">Bond Therapy order</p><div className="mt-1 flex items-center justify-between gap-3"><h1 className="text-xl font-semibold text-foreground">{order.orderNumber}</h1><span className="rounded-full bg-background px-2.5 py-1 text-xs font-semibold">{order.status.replaceAll("_", " ")}</span></div><p className="mt-1 text-sm text-muted">{order.client.salonName} · {order.client.city}</p></div><div className="space-y-4 p-5"><div className="overflow-hidden rounded-lg border"><div className="grid grid-cols-[1fr_auto] bg-background px-3 py-2 text-xs font-semibold text-muted"><span>Product</span><span>Qty</span></div>{order.items.map((item) => <div key={item.id} className="grid grid-cols-[1fr_auto] border-t px-3 py-2.5 text-sm"><span>{item.product.name}</span><span className="font-semibold">{item.quantity}</span></div>)}</div>{["SUBMITTED", "UNDER_REVIEW"].includes(order.status) && <><Input value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Reason required only when rejecting" /><div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={() => update("APPROVED")}><Check size={15} />Accept order</Button><Button variant="secondary" disabled={busy || !comment.trim()} onClick={() => update("REJECTED")}><XCircle size={15} />Reject</Button></div></>}{order.status === "APPROVED" && <div className="space-y-3"><Input value={invoice} onChange={(event) => setInvoice(event.target.value)} placeholder="Tally / Marg invoice number" /><div className="grid grid-cols-2 gap-2"><label className="flex h-11 cursor-pointer items-center justify-center gap-2 rounded-lg border px-3 text-sm font-medium"><Camera size={16} />Take photo<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" capture="environment" className="sr-only" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label><label className="flex h-11 cursor-pointer items-center justify-center gap-2 rounded-lg border px-3 text-sm font-medium"><FileUp size={16} />PDF / photo<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp,image/heic,image/heif" className="sr-only" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label></div>{file && <p className="truncate text-xs text-muted">Added: {file.name}</p>}<Button disabled={busy || !invoice.trim() || !file} onClick={() => update("DISTRIBUTOR_FULFILLED")}><PackageCheck size={15} />Confirm invoice &amp; dispatch</Button></div>}{error && <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-danger">{error}</div>}</div></section></main>;
}
