"use client";

import { ArrowLeft, CalendarPlus, CheckCircle2, Clock3, FileText, Flag, MapPin, MessageCircle, NotebookPen, Phone, Plus, ShoppingBag, Star, UserRound, X } from "lucide-react";
import Link from "next/link";
import { type FormEvent, type ReactNode, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Detail = { client: { id: string; salonName: string; category: string; status: string; ownerName: string | null; managerName: string | null; primaryContact: string; whatsappNumber: string | null; email: string | null; fullAddress: string | null; area: string | null; city: string; googleMapsUrl: string | null; territory: string | null; overallRating: number | null; potential: string | null; version: number; assignedSalesperson: { name: string } | null; assignedTrainer: { name: string } | null }; activities: Activity[]; openActions: Activity[]; nextVisit: Activity | null; salesSnapshot: Record<string, number | null>; productSnapshot: { purchased: unknown[]; lastProduct: string | null; mostPurchased: string | null; demos: unknown[]; samples: unknown[] } };
type Activity = { id: string; type: string; status: string; purpose: string | null; personMet: string | null; note: string | null; scheduledAt: string | null; createdAt: string; createdBy?: { name: string } };
const pretty = (value?: string | null) => value ? value.toLowerCase().split("_").map((part) => part[0]?.toUpperCase() + part.slice(1)).join(" ") : "Not set";
const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not scheduled";

export function Salon360({ initial }: { initial: Detail }) {
  const [detail, setDetail] = useState(initial); const [activityType, setActivityType] = useState<string | null>(null); const [error, setError] = useState("");
  const client = detail.client;
  const reload = async () => { const response = await fetch(`/api/clients/${client.id}`, { cache: "no-store" }); if (response.ok) setDetail(await response.json() as Detail); };
  return <div className="space-y-4 pb-6">
    <Link href="/dashboard/clients" className="inline-flex items-center gap-1.5 text-xs font-semibold text-muted hover:text-brand"><ArrowLeft size={15} />Back to Clients</Link>
    <section className="rounded-xl border bg-white p-4 shadow-[0_3px_12px_rgba(23,35,31,0.04)] sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold tracking-[-0.02em] text-foreground">{client.salonName}</h2><Status value={client.status} /></div><p className="mt-1 text-sm text-muted">{pretty(client.category)}{client.ownerName ? ` · ${client.ownerName}` : ""}{client.city ? ` · ${client.city}` : ""}</p><div className="mt-4 grid gap-2 text-xs text-muted sm:grid-cols-3"><p><UserRound className="mr-1 inline" size={14} />{client.ownerName || client.managerName || "Owner not set"}</p><p><MapPin className="mr-1 inline" size={14} />{[client.area, client.city].filter(Boolean).join(", ")}</p><p><Star className="mr-1 inline fill-warning text-warning" size={14} />{client.overallRating ? `${client.overallRating}/5 overall` : "Rating not set"}</p></div></div><div className="flex shrink-0 gap-2"><a href={`tel:${client.primaryContact}`} className="grid size-10 place-items-center rounded-lg border text-foreground hover:bg-brand-soft" aria-label="Call salon"><Phone size={17} /></a>{client.whatsappNumber && <a href={`https://wa.me/${client.whatsappNumber.replace(/\D/g, "")}`} className="grid size-10 place-items-center rounded-lg border text-foreground hover:bg-brand-soft" aria-label="WhatsApp salon"><MessageCircle size={17} /></a>}{client.googleMapsUrl && <a href={client.googleMapsUrl} target="_blank" rel="noreferrer" className="grid size-10 place-items-center rounded-lg border text-foreground hover:bg-brand-soft" aria-label="Open directions"><MapPin size={17} /></a>}</div></div><div className="mt-5 grid grid-cols-2 gap-2 sm:flex sm:flex-wrap"><QuickAction icon={CalendarPlus} label="Visit" onClick={() => setActivityType("VISIT")} /><QuickAction icon={Clock3} label="Follow-up" onClick={() => setActivityType("FOLLOW_UP")} /><QuickAction icon={Flag} label="Demo" onClick={() => setActivityType("DEMO")} /><QuickAction icon={ShoppingBag} label="Sample" onClick={() => setActivityType("SAMPLE")} /><QuickAction icon={NotebookPen} label="Note" onClick={() => setActivityType("NOTE")} /></div></section>
    {error && <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2.5 text-xs text-danger" role="alert">{error}</div>}
    <section className="grid gap-3 sm:grid-cols-3"><Metric label="Lifetime sales" value={detail.salesSnapshot.lifetimeSales == null ? "₹0" : `₹${detail.salesSnapshot.lifetimeSales.toLocaleString("en-IN")}`} /><Metric label="Outstanding" value={detail.salesSnapshot.outstanding == null ? "₹0" : `₹${detail.salesSnapshot.outstanding.toLocaleString("en-IN")}`} /><Metric label="Last order" value={detail.salesSnapshot.lastOrder == null ? "No orders yet" : String(detail.salesSnapshot.lastOrder)} /></section>
    <section className="rounded-xl border bg-white shadow-[0_3px_12px_rgba(23,35,31,0.04)]"><SectionTitle icon={Flag} title="Open actions" subtitle="What needs attention next" />{detail.openActions.length ? <div className="divide-y">{detail.openActions.map((activity) => <ActivityRow key={activity.id} activity={activity} />)}</div> : <Empty text="No pending actions" />}</section>
    <section className="rounded-xl border bg-white shadow-[0_3px_12px_rgba(23,35,31,0.04)]"><SectionTitle icon={CalendarPlus} title="Next visit" subtitle={detail.nextVisit ? formatDate(detail.nextVisit.scheduledAt) : "Plan the next relationship touchpoint"} />{detail.nextVisit ? <div className="px-4 pb-4 text-sm text-foreground">{detail.nextVisit.purpose || "Visit scheduled"}{detail.nextVisit.personMet ? ` · ${detail.nextVisit.personMet}` : ""}</div> : <Empty text="No visit scheduled" action={<Button variant="secondary" className="h-9" onClick={() => setActivityType("VISIT")}><Plus size={14} />Schedule visit</Button>} />}</section>
    <section className="rounded-xl border bg-white shadow-[0_3px_12px_rgba(23,35,31,0.04)]"><SectionTitle icon={ShoppingBag} title="Products" subtitle="Connected product history" /><Empty text="No product history yet" /></section>
    <section className="rounded-xl border bg-white shadow-[0_3px_12px_rgba(23,35,31,0.04)]"><SectionTitle icon={FileText} title="Recent activity" subtitle="Latest relationship notes and actions" />{detail.activities.length ? <div className="divide-y">{detail.activities.map((activity) => <ActivityRow key={activity.id} activity={activity} />)}</div> : <Empty text="No activity recorded yet" />}</section>
    {activityType && <ActivityForm clientId={client.id} type={activityType} onClose={() => setActivityType(null)} onSaved={async () => { setActivityType(null); await reload(); }} onError={setError} />}
  </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border bg-white p-4 shadow-[0_2px_8px_rgba(23,35,31,0.03)]"><p className="text-xs text-muted">{label}</p><p className="mt-1.5 text-base font-semibold text-foreground">{value}</p></div>; }
function Status({ value }: { value: string }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold ${value === "ACTIVE" ? "bg-[#e8f5ef] text-[#1f6b57]" : value === "INACTIVE" ? "bg-gray-100 text-muted" : "bg-warning-soft text-warning"}`}>{pretty(value)}</span>; }
function QuickAction({ icon: Icon, label, onClick }: { icon: typeof Plus; label: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border px-3 text-xs font-semibold text-foreground hover:border-brand/30 hover:bg-brand-soft"><Icon size={15} />{label}</button>; }
function SectionTitle({ icon: Icon, title, subtitle }: { icon: typeof Plus; title: string; subtitle: string }) { return <div className="flex items-center gap-3 border-b px-4 py-3.5 sm:px-5"><span className="grid size-8 place-items-center rounded-lg bg-brand-soft text-brand"><Icon size={16} /></span><div><h3 className="text-sm font-semibold text-foreground">{title}</h3><p className="mt-0.5 text-xs text-muted">{subtitle}</p></div></div>; }
function ActivityRow({ activity }: { activity: Activity }) { return <div className="flex gap-3 px-4 py-3.5 sm:px-5"><span className="mt-0.5 grid size-7 shrink-0 place-items-center rounded-full bg-brand-soft text-brand"><CheckCircle2 size={15} /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-semibold text-foreground">{pretty(activity.type)}</p><span className="text-[11px] text-muted">{activity.status === "OPEN" && activity.scheduledAt ? formatDate(activity.scheduledAt) : formatDate(activity.createdAt)}</span></div>{(activity.purpose || activity.personMet) && <p className="mt-1 text-xs text-muted">{[activity.purpose, activity.personMet].filter(Boolean).join(" · ")}</p>}{activity.note && <p className="mt-1 text-xs leading-5 text-muted">{activity.note}</p>}</div></div>; }
function Empty({ text, action }: { text: string; action?: ReactNode }) { return <div className="px-4 py-6 text-center sm:px-5"><p className="text-xs text-muted">{text}</p>{action && <div className="mt-3">{action}</div>}</div>; }

function ActivityForm({ clientId, type, onClose, onSaved, onError }: { clientId: string; type: string; onClose: () => void; onSaved: () => Promise<void>; onError: (message: string) => void }) { const [purpose, setPurpose] = useState(""); const [personMet, setPersonMet] = useState(""); const [note, setNote] = useState(""); const [scheduledAt, setScheduledAt] = useState(""); const [saving, setSaving] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const response = await fetch(`/api/clients/${clientId}/activities`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type, purpose, personMet, note, scheduledAt: scheduledAt ? new Date(scheduledAt).toISOString() : undefined }) }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.message || "Unable to save activity."); await onSaved(); } catch (cause) { onError(cause instanceof Error ? cause.message : "Unable to save activity."); setSaving(false); } }; return <div className="fixed inset-0 z-50 grid place-items-end bg-[#10201b]/40 p-0 backdrop-blur-[1px] sm:place-items-center sm:p-4" role="dialog" aria-modal="true" aria-label={`Add ${pretty(type)}`}><form onSubmit={submit} className="w-full rounded-t-xl border bg-white p-5 shadow-[0_20px_48px_rgba(16,32,27,0.18)] sm:max-w-lg sm:rounded-xl"><div className="flex items-start justify-between"><div><h2 className="text-base font-semibold text-foreground">Add {pretty(type)}</h2><p className="mt-1 text-xs text-muted">Only the information needed for this touchpoint.</p></div><button type="button" onClick={onClose} className="grid size-8 place-items-center rounded-lg text-muted hover:bg-background" aria-label="Close"><X size={17} /></button></div><div className="mt-5 space-y-4"><Field label={type === "NOTE" ? "Title" : "Purpose"}><Input value={purpose} onChange={(event) => setPurpose(event.target.value)} autoFocus maxLength={160} /></Field>{type !== "NOTE" && <Field label="Person met"><Input value={personMet} onChange={(event) => setPersonMet(event.target.value)} maxLength={120} /></Field>}{type !== "NOTE" && <Field label="Scheduled date and time"><Input value={scheduledAt} onChange={(event) => setScheduledAt(event.target.value)} type="datetime-local" /></Field>}<label className="block space-y-1.5"><span className="text-xs font-medium text-foreground">Notes</span><textarea value={note} onChange={(event) => setNote(event.target.value)} rows={4} maxLength={1000} className="w-full resize-y rounded-lg border bg-white px-3 py-2.5 text-[13px] outline-none focus:border-brand focus:ring-2 focus:ring-brand/10" /></label></div><div className="mt-5 flex flex-col-reverse gap-2 border-t pt-4 sm:flex-row sm:justify-end"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving…" : "Save activity"}</Button></div></form></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block space-y-1.5"><span className="text-xs font-medium text-foreground">{label}</span>{children}</label>; }
