ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'MASK';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'KIT';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'DEVELOPER';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'OIL_SERUM';
ALTER TYPE "ProductCategory" ADD VALUE IF NOT EXISTS 'LIQUID';

ALTER TABLE "Product" ADD COLUMN "variant" TEXT;
ALTER TABLE "Product" DROP COLUMN "imageUrl";
